'use client';
import { useRef, useState, type Dispatch, type SetStateAction } from 'react';
import { AudioLines, Camera, Cpu, Download, FileText, LoaderCircle, Trash2, Upload, Waves, X } from 'lucide-react';
import { Dialog, DialogContent, DialogTitle, DialogDescription, DialogClose } from '@/components/ui/dialog';
import { readKnowledge } from '@/services/knowledge';
import type { Knowledge, Mode, Visual } from '@/lib/neuro';
import { visualNames, type Modal } from './Workspace';
type Props={modal:Modal;setModal:(v:Modal)=>void;mode:Mode;setMode:(v:Mode)=>void;configured:boolean;checked:boolean;preference:'auto'|Visual;setPreference:(v:'auto'|Visual)=>void;docs:Knowledge[];setDocs:Dispatch<SetStateAction<Knowledge[]>>;onNotice:(v:string)=>void;onClear:()=>void;onExport:()=>void};
export function SessionDialog(p:Props){
  const fileRef=useRef<HTMLInputElement>(null);const [reading,setReading]=useState(false);
  const upload=async(files:FileList|null)=>{if(!files||reading)return;setReading(true);try{const added:Knowledge[]=[];for(const file of Array.from(files).slice(0,5-p.docs.length))added.push(await readKnowledge(file));p.setDocs(v=>[...v,...added].slice(0,5));p.onNotice(`已提取 ${added.length} 份资料文字，可在对话中按关键词检索。`)}catch(error){p.onNotice(error instanceof Error?error.message:'资料读取失败。')}finally{setReading(false);if(fileRef.current)fileRef.current.value=''}};
  return <Dialog open={p.modal!==null} onOpenChange={open=>{if(!open)p.setModal(null)}}><DialogContent className="neuro-dialog" showCloseButton={false}><DialogClose className="dialog-close icon-button" aria-label="关闭窗口"><X size={18}/></DialogClose><DialogTitle>{p.modal==='settings'?'生成服务与解释偏好':p.modal==='knowledge'?'本次会话资料':p.modal==='clear'?'开始新的会话？':'隐私与数据'}</DialogTitle><DialogDescription>{p.modal==='settings'?'选择生成方式和默认解释偏好。':p.modal==='knowledge'?'支持文字型 PDF、TXT、Markdown；PPT 请先导出为 PDF。':p.modal==='clear'?'将关闭摄像头与语音，清除照片、对话、资料和状态记录，此操作无法撤销。':'摄像头画面与快照仅在当前浏览器内显示。'}</DialogDescription>
    {p.modal==='settings'&&<><div className="service-detail"><Cpu size={22}/><div><strong>DeepSeek 生成服务</strong><span>{!p.checked?'正在检查…':p.configured?'已配置，可切换在线生成':'未配置服务端密钥'}</span></div><span className={p.configured?'connected':'simulation-badge'}>{p.configured?'可用':'待接入'}</span></div><label className="settings-field">生成方式<select value={p.mode} onChange={e=>p.setMode(e.target.value as Mode)}><option value="demo">本地演示 · 有限知识范围</option><option value="live" disabled={!p.configured}>DeepSeek · 在线问答{!p.configured?'（待配置）':''}</option></select></label><label className="settings-field">默认解释方式<select value={p.preference} onChange={e=>p.setPreference(e.target.value as 'auto'|Visual)}><option value="auto">跟随状态自动适配</option>{Object.entries(visualNames).map(([v,name])=><option key={v} value={v}>{name}优先</option>)}</select></label><p className="settings-note">在线生成仅发送对话、模拟状态摘要和相关资料片段。摄像头画面与照片不会发送。脑电和视觉识别仍为模拟；真实推理需要接入设备与模型服务。</p><details className="settings-note"><summary>部署配置说明</summary><p>在服务端设置 DEEPSEEK_API_KEY 后重新发布即可启用。不要在对话框填写密钥。</p></details></>}
    {p.modal==='knowledge'&&<><input ref={fileRef} type="file" accept=".pdf,.txt,.md" hidden multiple onChange={e=>void upload(e.target.files)}/><button className="dropzone" onClick={()=>fileRef.current?.click()} disabled={reading||p.docs.length>=5}>{reading?<LoaderCircle className="spin" size={24}/>:<Upload size={24}/>}<strong>{reading?'正在提取文字…':'选择资料文件'}</strong><span>最多 5 份 · 每份 10 MB · PDF 最多 80 页</span></button>{p.docs.map(doc=><div className="knowledge-item" key={doc.id}><FileText size={18}/><div><strong>{doc.name}</strong><span>{doc.text.length.toLocaleString()} 字符{doc.pages?` · ${doc.pages} 页`:''} · 已提取</span></div><button className="icon-button" title={`移除 ${doc.name}`} onClick={()=>p.setDocs(v=>v.filter(d=>d.id!==doc.id))}><Trash2 size={16}/></button></div>)}<p className="settings-note">输入“根据资料解释……”和具体关键词进行检索。演示模式展示原文片段；在线模式将相关片段交给生成服务。不会永久保存文件。</p></>}
    {p.modal==='privacy'&&<><div className="privacy-item"><Camera size={22}/><div><strong>摄像头与照片</strong><p>仅在本机预览。断开连接会停止视频轨道，照片可在预览区删除。</p></div></div><div className="privacy-item"><Waves size={22}/><div><strong>状态与会话</strong><p>脑电为模拟数据。状态轨迹保留最近 60 秒，对话保留最近 40 轮。刷新或新建会话会清除对话记录。</p></div></div><div className="privacy-item"><AudioLines size={22}/><div><strong>语音输入</strong><p>使用浏览器语音识别，音频可能由浏览器厂商的服务处理。转写后由你确认发送。</p></div></div><button className="outline-button" onClick={()=>p.setModal('clear')}>清除本次会话</button></>}
    {p.modal==='clear'&&<div className="dialog-actions"><button className="outline-button" onClick={p.onExport}><Download size={15}/>先导出记录</button><button className="danger-button" onClick={p.onClear}><Trash2 size={15}/>清除并开始</button></div>}
  </DialogContent></Dialog>;
}
