'use client';
import { ArrowRight, Download, History } from 'lucide-react';
import { BrainGraph } from './BrainGraph';
import { Meter, percent, visualNames, type SessionEvent } from './Workspace';
import { profiles, type Snapshot, type Policy, type Scene, type Turn } from '@/lib/neuro';
export function EngineView({snapshot,policy,scene,windowIndex}:{snapshot:Snapshot;policy:Policy;scene:Scene;windowIndex:number}){
  return <section className="engine-page"><div className="engine-banner"><div><p className="eyebrow">脑电自主技术模块</p><h2>TCG-3DNet</h2><p>每个观察窗依据当前通道完整时间—频带轨迹，重新估计样本专属软图。</p><span className="simulation-badge">架构与模拟推理展示 · 未加载训练权重</span></div><BrainGraph snapshot={snapshot} windowIndex={windowIndex} large/></div>
    <div className="technical-pipeline">{[['01','五频带差分熵','δ · θ · α · β · γ'],['02','完整通道轨迹','重叠观察窗 → 轨迹编码'],['03','轨迹条件化动态软图','当前样本专属通道关系'],['04','多上下文图建模','Multi-Context TC-G3D'],['05','固定通道时序融合','QKV-BiMamba'],['06','状态读出','48 维脑电状态嵌入']].map(([n,title,sub])=><div key={n}><span>{n}</span><strong>{title}</strong><small>{sub}</small></div>)}</div>
    <div className="engine-details"><section><h3>状态嵌入 <small>48 维 · 模拟</small></h3><div className="embedding-bars">{snapshot.eeg.embedding.map((v,i)=><div key={i} title={`维度 ${i+1}: ${v}`}><i style={{height:`${Math.abs(v)*85+5}%`,background:v<0?'#abc2cb':'#3d788b'}}/></div>)}</div><div className="metrics-grid">{[['额区响应',snapshot.eeg.frontal],['颞区响应',snapshot.eeg.temporal],['图变化量',snapshot.eeg.graphChange],['状态稳定性',snapshot.eeg.stability]].map(([name,value])=><div key={name}><span>{name}</span><strong>{Number(value).toFixed(2)}</strong></div>)}</div></section><section><h3>场景驱动的多模态融合</h3><p>加权融合传感状态与对话语义。下列权重是可配置的演示规则，不代表训练模型的性能。</p>{snapshot.weights.map((weight,i)=><Meter key={i} label={['视觉','脑电','对话'][i]} value={weight}/>)}<p className="rule-note">{scene}风险阈值：{percent(profiles[scene].threshold)}% · {policy.reason}</p></section></div>
    <section className="trace-section"><h3>本轮决策轨迹</h3><div className="trace-steps">{[['场景',scene],['视觉',`注意力 ${percent(snapshot.vision.attention)}%`],['脑电',`消极 ${percent(snapshot.eeg.negative)}%`],['对话',snapshot.dialogue.intent],['融合',snapshot.human.emotion],['策略',policy.strategy],['生成',`${policy.length} · ${visualNames[policy.visual]}`]].map(([title,value],i)=><div key={title}><small>0{i+1} / {title}</small><strong>{value}</strong></div>)}</div></section>
  </section>;
}
export function HistoryView({turns,events,onExport,onBack}:{turns:Turn[];events:SessionEvent[];onExport:()=>void;onBack:()=>void}){
  return <section className="history-page"><div className="history-toolbar"><div><strong>{turns.length} 轮对话</strong><span>{events.length} 条事件 · 仅本次会话</span></div><button className="outline-button" onClick={onExport}><Download size={15}/>导出会话</button></div><div className="history-columns"><section><h3>适配记录</h3>{turns.length?turns.map(turn=><div className="history-turn" key={turn.id}><time>{turn.time}</time><div><strong>{turn.question}</strong><p>{turn.snapshot.human.emotion} <ArrowRight size={13}/> {turn.policy.strategy} <ArrowRight size={13}/> {visualNames[turn.policy.visual]}</p><small>{turn.reply.source==='demo'?'模拟生成':turn.reply.source==='safety'?'安全规则':'DeepSeek'} · {turn.scene}</small></div></div>):<div className="empty-history"><History size={30}/><p>开始一轮对话后，状态与策略变化会记录在这里。</p><button className="outline-button" onClick={onBack}>开始交互<ArrowRight size={14}/></button></div>}</section><section><h3>会话事件</h3>{events.map(event=><div className="event-row" key={event.id}><time>{event.time}</time><strong>{event.label}</strong><p>{event.detail}</p></div>)}</section></div></section>;
}
