'use client';
import { useEffect, useMemo, useRef, useState } from 'react';
import { Activity, ArrowRight, ArrowUpRight, BookOpen, BrainCircuit, Check, ChevronRight, CircleHelp, Cpu, Download, FileText, Focus, History, Layers3, LoaderCircle, Maximize2, MessageSquare, Mic, Network, Pause, Play, Plus, RotateCcw, Settings2, ShieldCheck, Square, Upload, Volume2, Waves, X } from 'lucide-react';
import { Tabs, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { CameraPanel } from './CameraPanel';
import { BrainGraph } from './BrainGraph';
import { ResponseVisual } from './ResponseVisual';
import { TurnDecision } from './TurnDecision';
import { mergeSessionTurns } from '@/lib/session';
import { SessionDialog } from './SessionDialog';
import { EngineView, HistoryView } from './Views';
import { SpeechInput, type RecognitionConstructor, type SpeechStatus } from '@/services/speech';
import { VoiceInputStatus } from './VoiceInputStatus';
import { decide, demoReply, fuse, labels, profiles, retrieve, simulationPrompts, scenarios, scenes, understand, type Knowledge, type Mode, type Reply, type Scenario, type Scene, type Turn, type Visual } from '@/lib/neuro';
import '@/app/workspace.css';
import '@/app/studio.css';
import '@/app/atelier.css';
export type SessionEvent={id:string;time:string;label:string;detail:string};
export type Modal='settings'|'knowledge'|'privacy'|'clear'|null;
type Point={time:number;value:number;state:Scenario};
export const visualNames:Record<Visual,string>={text:'文字',diagram:'图示',animation:'动画',steps:'步骤'};
const demoSteps=[{label:'正常提问',text:'为什么 GCN 需要邻接矩阵？',state:'normal'},{label:'出现困惑',text:'还是没太懂。',state:'confused'},{label:'调整解释',text:'还是不懂，太复杂了，简单一点。',state:'frustrated'},{label:'理解恢复',text:'我理解了，可以继续。',state:'recovered'}] as const;
export const percent=(n:number)=>Math.round(n*100);
export function Meter({label,value,warn=false}:{label:string;value:number;warn?:boolean}){return <div className="meter"><span>{label}</span><div><i style={{width:`${percent(value)}%`}} className={warn?'warn':''}/></div><b>{percent(value)}<small>%</small></b></div>}

export default function Workspace(){
  const [view,setView]=useState('workspace');
  const [scene,setScene]=useState<Scene>('学习'),[detected,setDetected]=useState<Scene>('办公'),[manual,setManual]=useState(true);
  const activeScene=manual?scene:detected;
  const [scenario,setScenario]=useState<Scenario>('normal'),[dialogue,setDialogue]=useState(()=>understand(''));
  const [windowIndex,setWindowIndex]=useState(0),[streaming,setStreaming]=useState(true),[points,setPoints]=useState<Point[]>([]),[range,setRange]=useState(60);
  const [archivedTurns,setArchivedTurns]=useState<Turn[]>([]);
  const [turns,setTurns]=useState<Turn[]>([]),[input,setInput]=useState(''),[pending,setPending]=useState(false),[pendingText,setPendingText]=useState('');
  const [mode,setMode]=useState<Mode>('demo'),[configured,setConfigured]=useState(false),[serviceChecked,setServiceChecked]=useState(false);
  const [preference,setPreference]=useState<'auto'|Visual>('auto'),[overrides,setOverrides]=useState<Record<string,Visual>>({});
  const [events,setEvents]=useState<SessionEvent[]>([]),[modal,setModal]=useState<Modal>(null),[docs,setDocs]=useState<Knowledge[]>([]);
  const [notice,setNotice]=useState(''),[chatError,setChatError]=useState(''),[speaking,setSpeaking]=useState<string|null>(null);
  const [cameraEpoch,setCameraEpoch]=useState(0);
  const [cameraStatus,setCameraStatus]=useState('未连接'),[demoStep,setDemoStep]=useState(-1),[focusMode,setFocusMode]=useState(false);
  const [voiceStatus,setVoiceStatus]=useState<SpeechStatus>({phase:'idle',message:''});
  const listening=voiceStatus.phase!=='idle';
  const messagesEnd=useRef<HTMLDivElement>(null),abort=useRef<AbortController|null>(null),lock=useRef(false),recognition=useRef<SpeechInput|null>(null);
  const snapshot=useMemo(()=>fuse(activeScene,scenario,dialogue,windowIndex),[activeScene,scenario,dialogue,windowIndex]);
  const policy=useMemo(()=>decide(activeScene,snapshot.human,preference),[activeScene,snapshot,preference]);
  const latest=turns.at(-1),profile=profiles[activeScene];
  const sessionTurns=useMemo(()=>mergeSessionTurns(archivedTurns,turns),[archivedTurns,turns]);
  const archiveConversation=()=>setArchivedTurns(previous=>mergeSessionTurns(previous,turns));
  const log=(label:string,detail:string)=>setEvents(v=>[{id:crypto.randomUUID(),time:new Date().toLocaleTimeString('zh-CN',{hour12:false}),label,detail},...v].slice(0,100));
  useEffect(()=>{fetch('/api/chat').then(r=>r.ok?r.json():Promise.reject()).then(data=>setConfigured((data as {configured?:boolean}).configured===true)).catch(()=>setConfigured(false)).finally(()=>setServiceChecked(true));return()=>{abort.current?.abort();recognition.current?.cancel();window.speechSynthesis?.cancel()}},[]);
  useEffect(()=>{const hide=()=>{if(document.hidden){recognition.current?.cancel();setVoiceStatus({phase:'idle',message:''})}};document.addEventListener('visibilitychange',hide);return()=>document.removeEventListener('visibilitychange',hide)},[]);
  useEffect(()=>{if(!streaming)return;const timer=setInterval(()=>setWindowIndex(i=>i+1),3000);return()=>clearInterval(timer)},[streaming]);
  useEffect(()=>{setPoints(old=>[...old,{time:Date.now(),value:snapshot.eeg.negative,state:scenario}].filter(p=>Date.now()-p.time<=60000).slice(-40))},[windowIndex,scenario]);
  useEffect(()=>{if(!turns.length&&!pending)return;const panel=messagesEnd.current?.parentElement;panel?.scrollTo({top:panel.scrollHeight,behavior:'smooth'})},[turns,pending]);
  useEffect(()=>{if(!notice)return;const timer=setTimeout(()=>setNotice(''),7000);return()=>clearTimeout(timer)},[notice]);
  const submit=async(text:string,forced?:Scenario,asScene?:Scene,forceDemo=false)=>{
    if(lock.current||!text.trim())return;
    recognition.current?.cancel();setVoiceStatus({phase:'idle',message:''});
    const targetScene=asScene??activeScene,targetDialogue=understand(text,turns.map(t=>t.question));
    const next=forced??(targetDialogue.recovery?'recovered':targetDialogue.fatigue>.7?'fatigued':targetDialogue.confusion>.7?(targetDialogue.repeated?'frustrated':'confused'):scenario);
    const nextSnapshot=fuse(targetScene,next,targetDialogue,windowIndex),nextPolicy=decide(targetScene,nextSnapshot.human,preference);
    setScenario(next);setDialogue(targetDialogue);setInput('');setChatError('');setPending(true);setPendingText(text);lock.current=true;
    const controller=new AbortController();abort.current=controller;
    try{
      let reply:Reply;
      if(mode==='demo'||forceDemo)reply=demoReply(text,targetScene,nextSnapshot,nextPolicy,latest?.reply.topic??'other',docs);
      else{
        const response=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},signal:controller.signal,body:JSON.stringify({message:text,mode,scene:targetScene,scenario:next,preference,topic:latest?.reply.topic??'other',history:turns.slice(-6).flatMap(t=>[{role:'user',content:t.question},{role:'assistant',content:t.reply.text}]),knowledge:retrieve(text,docs).map((d,i)=>({id:String(i),name:d.name,text:d.text}))})});
        const data=await response.json() as {error?:string;reply:Reply};if(!response.ok)throw new Error(data.error||'生成失败，请稍后重试。');reply=data.reply;
      }
      if(controller.signal.aborted)return;
      setTurns(v=>[...v,{id:crypto.randomUUID(),question:text,reply,snapshot:nextSnapshot,policy:nextPolicy,time:new Date().toLocaleTimeString('zh-CN',{hour12:false}),scene:targetScene}].slice(-40));
      log('交互',`${targetScene} · ${labels[next]} → ${nextPolicy.strategy} → ${visualNames[nextPolicy.visual]}`);
    }catch(err){if(!controller.signal.aborted){setChatError(err instanceof Error?err.message:'请求失败，请重试。');setInput(text)}}finally{if(abort.current===controller){lock.current=false;setPending(false);abort.current=null;}}
  };
  const simulate=(next:Scenario)=>{const prompt=simulationPrompts[next];setScenario(next);setDialogue(understand(prompt,turns.map(t=>t.question)));log('状态模拟',`${labels[scenario]} → ${labels[next]}`);if(latest)void submit(prompt,next)};
  const resetContext=(archive=true)=>{if(archive)archiveConversation();window.speechSynthesis?.cancel();setSpeaking(null);recognition.current?.cancel();setVoiceStatus({phase:'idle',message:''});setScenario('normal');setDialogue(understand(''));setDemoStep(-1);setTurns([]);setChatError('')};
  const changeScene=(next:Scene)=>{setScene(next);setManual(true);resetContext();log('场景',`采用手动场景：${next}`)};
  const demo=(step?:number)=>{if(pending)return;const next=step??(demoStep>=3?0:demoStep+1);setDemoStep(next);setScene('学习');setManual(true);setMode('demo');setView('workspace');if(next===0){archiveConversation();setTurns([]);}void submit(demoSteps[next].text,demoSteps[next].state,'学习',true)};
  const feedback=(turn:Turn,yes:boolean)=>{setTurns(v=>v.map(t=>t.id===turn.id?{...t,feedback:yes?'yes':'no'}:t));void submit(yes?'我理解了，可以继续。':'还是不懂，请换一种方式。',yes?'recovered':'frustrated')};
  const checkAnswer=(correct:boolean)=>{setScenario(correct?'recovered':'confused');setDialogue(understand(correct?'理解了':'没懂'));log('理解确认',correct?'测验回答正确，建议逐步进阶':'测验回答有误，继续巩固解释');setNotice(correct?'回答正确，策略已调整为巩固后进阶。':'已记录理解受阻，下一轮将降低难度。')};
  const speak=(turn:Turn)=>{if(!window.speechSynthesis){setNotice('当前浏览器不支持语音朗读。');return;}window.speechSynthesis.cancel();if(speaking===turn.id){setSpeaking(null);return;}const utterance=new SpeechSynthesisUtterance(turn.reply.text);utterance.lang='zh-CN';utterance.rate=.95;utterance.onend=()=>setSpeaking(null);utterance.onerror=()=>{setSpeaking(null);setNotice('朗读未完成，请检查浏览器语音支持。')};setSpeaking(turn.id);window.speechSynthesis.speak(utterance)};
  const voice=()=>{
    if(listening){recognition.current?.stop();return;}
    window.speechSynthesis?.cancel();setSpeaking(null);
    if(!window.isSecureContext){setVoiceStatus({phase:'idle',message:'语音输入需要安全连接，请使用 HTTPS 网址。',error:true});return;}
    const browser=window as unknown as {SpeechRecognition?:RecognitionConstructor;webkitSpeechRecognition?:RecognitionConstructor};
    recognition.current??=new SpeechInput(setInput,setVoiceStatus);
    recognition.current.start(browser.SpeechRecognition??browser.webkitSpeechRecognition,input);
  };
  const download=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify({createdAt:new Date().toISOString(),scene:activeScene,sensorSource:'simulation',turns:sessionTurns,events},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='NeuroSense-会话记录.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),500);setNotice('已导出对话与决策摘要，不包含照片和资料正文。')};
  const clear=()=>{abort.current?.abort();abort.current=null;lock.current=false;setPending(false);setPendingText('');setArchivedTurns([]);recognition.current?.cancel();window.speechSynthesis?.cancel();setCameraEpoch(v=>v+1);setCameraStatus('未连接');setSpeaking(null);setVoiceStatus({phase:'idle',message:''});setOverrides({});setTurns([]);setEvents([]);setDocs([]);setPoints([]);setInput('');resetContext(false);setView('workspace');setFocusMode(false);setModal(null);setNotice('已清除对话、资料与状态摘要。')};
  const visiblePoints=points.filter(p=>(points.at(-1)?.time??0)-p.time<=range*1000);
  return <main className={`neuro-app studio ${focusMode?'focus-mode':''}`}>
    <div className="app-body"><header className="app-header"><div className="wordmark"><Waves size={25} strokeWidth={1.4}/>NeuroSense <span>AI</span></div><nav className="studio-navigation" aria-label="主要导航">{[{id:'workspace',label:'交互空间'},{id:'engine',label:'脑电引擎'},{id:'history',label:'会话记录'}].map(item=><button key={item.id} className={view===item.id?'selected':''} aria-current={view===item.id?'page':undefined} onClick={()=>setView(item.id)}>{item.label}</button>)}</nav><div className="header-actions"><button className="quiet-button studio-settings" onClick={()=>setModal('settings')} title="生成与偏好"><Settings2 size={17}/><span>设置</span></button><button className="outline-button" onClick={()=>setModal('clear')}><Plus size={15}/>新会话</button></div></header>
    <div className="workspace-title"><div className="studio-title"><h1>{view==='engine'?'脑电智能引擎':view==='history'?'会话记录':`${activeScene}会话`}</h1><span className="studio-session"><i/>{mode==='demo'?'演示模式':'在线生成'}</span></div><div className="title-actions"><button className="quiet-button" onClick={()=>setModal('privacy')}><ShieldCheck size={15}/>隐私</button><button className="primary-button" onClick={()=>demo()} disabled={pending}><Play size={15}/>{demoStep<0||demoStep===3?'体验完整流程':'继续演示'}<ArrowUpRight size={15}/></button></div></div>
    <div className="workspace-layout" hidden={view!=='workspace'}>
      <aside className="context-column"><div className="context-heading"><span>场景与输入</span><span className="mono">01</span></div><label className="scene-picker"><span>当前场景</span><select value={activeScene} onChange={e=>changeScene(e.target.value as Scene)} disabled={pending}>{scenes.map(s=><option key={s}>{s}</option>)}</select></label><p className="scene-focus">{profile.focus}</p><div className="scene-detection"><div><span>视觉场景 · 模拟</span><select aria-label="模拟视觉识别场景" value={detected} disabled={pending} onChange={e=>{setDetected(e.target.value as Scene);log('视觉场景',`模拟识别为${e.target.value}`);if(!manual)resetContext()}}>{scenes.map(s=><option key={s}>{s}</option>)}</select></div><span className="scene-priority">{manual&&scene!==detected?`识别为${detected}，采用手选${scene}`:manual?'场景一致，手动选择优先':'当前跟随视觉识别'}</span><button disabled={pending} onClick={()=>{setManual(!manual);resetContext();log('场景规则',manual?'跟随视觉识别':'切换手动优先')}}>{manual?'改为跟随视觉':'使用手动选择'}<ArrowRight size={12}/></button></div>
      <CameraPanel key={cameraEpoch} onStatus={setCameraStatus}/><div className="context-resources"><div className="section-label"><span><BookOpen size={15}/>会话资料</span><button className="icon-button" title="添加资料" onClick={()=>setModal('knowledge')}><Plus size={16}/></button></div>{docs.length?docs.map(d=><button className="file-item" key={d.id} onClick={()=>setModal('knowledge')}><FileText size={14}/><span>{d.name}</span><Check size={12}/></button>):<button className="upload-empty" onClick={()=>setModal('knowledge')}><Upload size={17}/><span>添加 PDF 或文字资料</span></button>}<p className="fine-print">本地提取文字，检索相关片段。</p></div><div className="input-sources"><span>信号来源</span><div><i className={cameraStatus==='本机预览'?'green':''}/>摄像头<b>{cameraStatus}</b></div><div><i className="amber"/>脑电与视觉状态<b>模拟</b></div><div><i className="green"/>对话语义<b>规则分析</b></div></div></aside>
      <section className="conversation-column" aria-label="自适应对话"><div className="conversation-heading"><div><span className="agent-mark"><BrainCircuit size={19}/></span><div><strong>对话</strong><span>{activeScene}场景 · {mode==='demo'?'本地演示':'在线生成'}</span></div></div><button className="icon-button" title={focusMode?'退出专注布局':'专注对话'} onClick={()=>setFocusMode(v=>!v)}><Maximize2 size={16}/></button></div><div className="adaptation-strip" key={scenario}><span><Activity size={14}/>{snapshot.human.emotion}</span><ArrowRight size={13}/><strong>{policy.strategy}</strong><span className="adapting-label">适配中</span></div>
      <div className="conversation-scroll" role="log" aria-live="polite" aria-relevant="additions">{!turns.length&&!pending&&<div className="conversation-empty"><p className="eyebrow">本次会话</p><h2>从一个问题开始。</h2><p>{profile.intro}</p><div className="suggested-prompts">{profile.prompts.map((text,i)=><button key={text} onClick={()=>void submit(text)}><span>0{i+1}</span>{text}<ArrowUpRight size={15}/></button>)}</div><div className="empty-note"><Waves size={14}/><span>{activeScene==='驾驶'||activeScene==='工业安全'?'可模拟疲劳，查看安全规则如何优先响应。':'提问后点击“困惑”，观察回答如何改变。'}</span></div></div>}
      {turns.map((turn,index)=>{const output=overrides[turn.id]??turn.policy.visual;return <article className="conversation-turn" key={turn.id}><div className="user-message"><p>{turn.question}</p><span>你 · {turn.time}</span></div><div className="assistant-message"><div className="assistant-identity"><BrainCircuit size={17}/><strong>NeuroSense</strong><span>{turn.reply.source==='deepseek'?'DeepSeek':turn.reply.source==='safety'?'安全规则':'演示回答'}</span></div><p className="answer-text">{turn.reply.text}</p>{turn.reply.citations&&<div className="citations">{turn.reply.citations.map((c,i)=><span key={`${c}-${i}`}><FileText size={12}/>{c}</span>)}</div>}{turn.reply.steps.length>0&&<Tabs value={output} onValueChange={v=>setOverrides(old=>({...old,[turn.id]:v as Visual}))}><TabsList className="output-tabs">{(Object.keys(visualNames) as Visual[]).map(v=><TabsTrigger key={v} value={v}>{visualNames[v]}</TabsTrigger>)}</TabsList></Tabs>}<ResponseVisual reply={turn.reply} mode={output} onAnswer={index===turns.length-1?checkAnswer:undefined}/><div className="answer-actions"><button onClick={()=>speak(turn)}><Volume2 size={14}/>{speaking===turn.id?'停止朗读':'朗读'}</button><button onClick={()=>{if(!navigator.clipboard){setNotice('请选中文字复制。');return;}void navigator.clipboard.writeText(turn.reply.text).then(()=>setNotice('回答已复制。')).catch(()=>setNotice('浏览器无法复制，请选中文字复制。'))}}>复制</button><details><summary>为什么这样回答 <ChevronRight size={12}/></summary><TurnDecision turn={turn}/></details></div>{index===turns.length-1&&<div className="feedback-row"><span>这样的解释合适吗？</span><button disabled={pending} onClick={()=>feedback(turn,true)}><Check size={14}/>理解了</button><button disabled={pending} onClick={()=>feedback(turn,false)}><RotateCcw size={14}/>换种方式</button></div>}</div></article>})}
      {pending&&<div className="pending-message"><p>{pendingText}</p><span><LoaderCircle className="spin" size={16}/>正在按当前策略组织回答…</span></div>}<div ref={messagesEnd}/></div>
      {chatError&&<div className="chat-error" role="alert">{chatError}<button onClick={()=>void submit(input)}>重试</button></div>}<div className="composer-area"><VoiceInputStatus status={voiceStatus} onStop={()=>recognition.current?.stop()} onRetry={voice}/><form className="composer" onSubmit={e=>{e.preventDefault();void submit(input)}}><textarea rows={2} maxLength={4000} aria-label="输入问题" value={input} onChange={e=>{recognition.current?.cancel();setVoiceStatus({phase:'idle',message:''});setInput(e.target.value)}} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.nativeEvent.isComposing){e.preventDefault();void submit(input)}}} placeholder="输入问题，或继续追问…"/><div className="composer-tools"><button type="button" title="添加资料" onClick={()=>setModal('knowledge')}><Plus size={18}/></button><button type="button" aria-label={listening?'完成语音输入':'语音输入'} aria-pressed={listening} disabled={pending||voiceStatus.phase==='stopping'} title={listening?'完成语音输入':'语音输入'} className={listening?'recording':''} onClick={voice}><Mic size={18}/></button><label><span>解释</span><select value={preference} onChange={e=>setPreference(e.target.value as 'auto'|Visual)} aria-label="回答形式偏好"><option value="auto">自动适配</option>{Object.entries(visualNames).map(([key,name])=><option key={key} value={key}>{name}优先</option>)}</select></label>{pending?<button type="button" className="send-button" title="停止生成" onClick={()=>{abort.current?.abort();setPending(false)}}><Square size={16}/></button>:<button type="submit" className="send-button" title="发送问题" disabled={!input.trim()}><ArrowUpRight size={20}/></button>}</div></form><p className="composer-caption"><span>回车发送 · Shift + 回车换行</span><span>{mode==='demo'?'有限知识演示':'仅发送文本与状态摘要'}</span></p></div></section>
      <aside className="intelligence-column"><div className="eeg-signal-section"><div className="intelligence-heading"><div><Waves size={17}/><strong>脑电智能引擎</strong></div><span className="simulation-badge">模拟数据</span></div><div className="engine-name"><h2>TCG-3DNet<span>自主算法架构</span></h2><button className="icon-button" title="查看完整技术链路" onClick={()=>setView('engine')}><ArrowUpRight size={17}/></button></div><BrainGraph snapshot={snapshot} windowIndex={windowIndex}/><div className="eeg-probabilities">{[['积极',snapshot.eeg.positive],['中性',snapshot.eeg.neutral],['消极',snapshot.eeg.negative]].map(([label,value])=><div key={label}><span>{label}</span><strong>{percent(Number(value))}<small>%</small></strong><i style={{width:`${percent(Number(value))}%`}}/></div>)}</div><div className="signal-timeline"><div><span>状态轨迹</span><div>{[30,60].map(v=><button key={v} className={range===v?'active':''} onClick={()=>setRange(v)}>{v} 秒</button>)}<button title={streaming?'暂停模拟流':'继续模拟流'} onClick={()=>setStreaming(v=>!v)}>{streaming?<Pause size={12}/>:<Play size={12}/>}</button></div></div><svg viewBox="0 0 300 44" preserveAspectRatio="none" aria-label="最近窗口的消极状态概率趋势"><path d="M0 36H300" stroke="#dce5e8"/>{visiblePoints.length>1&&<polyline points={visiblePoints.map((p,i)=>`${i*300/Math.max(1,visiblePoints.length-1)},${38-p.value*32}`).join(' ')} fill="none" stroke="#477b8d" strokeWidth="2"/>}</svg><small>消极概率 · {snapshot.human.trend} · {streaming?'每 3 秒更新':'已暂停'}</small></div></div><div className="state-decision-section"><div className="fusion-heading"><span><Layers3 size={15}/>人因状态融合</span><b>{percent(snapshot.human.confidence)}%<small> 演示置信度</small></b></div><div className="state-meters"><Meter label="困惑" value={snapshot.human.confusion} warn={snapshot.human.confusion>.6}/><Meter label="认知负荷" value={snapshot.human.load} warn={snapshot.human.load>.65}/><Meter label="注意力" value={snapshot.human.attention}/><Meter label="疲劳" value={snapshot.human.fatigue} warn={snapshot.human.fatigue>.65}/></div><div className="policy-compact" key={policy.strategy}><span><Focus size={15}/>策略智能体</span><strong>{policy.strategy}</strong><div><span>{policy.length}回答</span><span>{policy.difficulty}难度</span><span>{visualNames[policy.visual]}输出</span></div></div><button className="engine-link" onClick={()=>setView('engine')}>48 维嵌入 · 融合权重 · 决策依据<ArrowRight size={14}/></button></div></aside>
    </div>
    {view==='engine'&&<EngineView snapshot={snapshot} policy={policy} scene={activeScene} windowIndex={windowIndex}/>}
    {view==='history'&&<HistoryView turns={sessionTurns} events={events} onExport={download} onBack={()=>setView('workspace')}/>}
    <footer className="demo-dock"><div className="demo-label"><span><i/>状态模拟台</span><small>选择状态，比较回应方式</small></div><div className="scenario-buttons">{scenarios.map(s=><button disabled={pending} key={s} className={scenario===s?'active':''} aria-pressed={scenario===s} onClick={()=>simulate(s)}><i className={s}/>{labels[s]}</button>)}</div><div className="demo-progress">{demoSteps.map((step,i)=><button disabled={pending} key={step.label} title={`演示第${i+1}步：${step.label}`} className={demoStep===i?'current':demoStep>i?'done':''} onClick={()=>demo(i)}>{demoStep>i?<Check size={12}/>:<span>{i+1}</span>}<b>{step.label}</b></button>)}</div></footer></div>
    {notice&&<div className="toast-message" role="status"><CircleHelp size={17}/><span>{notice}</span><button title="关闭提示" onClick={()=>setNotice('')}><X size={16}/></button></div>}
    <SessionDialog modal={modal} setModal={setModal} mode={mode} setMode={setMode} configured={configured} checked={serviceChecked} preference={preference} setPreference={setPreference} docs={docs} setDocs={setDocs} onNotice={setNotice} onClear={clear} onExport={download}/>
  </main>;
}
