/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.chat.jsonc --include-runtime=false --env-interface=ChatWorkerEnv worker/env.d.ts` (hash: 9661d5b30e43ad6c46e37d44136591f3)
interface __BaseEnv_ChatWorkerEnv {
	CHAT_RATE_LIMIT: RateLimit;
	ALLOWED_ORIGIN: "https://modestteng.github.io";
	DEEPSEEK_MODEL: "deepseek-v4-flash";
	DEEPSEEK_API_KEY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./chat");
	}
	interface Env extends __BaseEnv_ChatWorkerEnv {}
}
interface ChatWorkerEnv extends __BaseEnv_ChatWorkerEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ALLOWED_ORIGIN" | "DEEPSEEK_MODEL" | "DEEPSEEK_API_KEY">> {}
}
